# Generated by Django 2.2.11 on 2020-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200524_1133'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['title', 'text'], name='app_questio_title_75eb98_idx'),
        ),
    ]
